import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { url } from "../../lib/env";
import { TextField, Button } from "@mui/material";
import { useState } from "react";
import Link from "next/link";

export default function CustomerMenu() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Customer Menu</h2>

        <div className={styles.grid}>
          <Link href={"/customer/manageAccountsCustomer"}>
            <a className={styles.card}>
              <h2>Manage Accounts &rarr;</h2>
            </a>
          </Link>

          <Link href={"/customer/deposit"}>
            <a className={styles.card}>
              <h2>Deposit &rarr;</h2>
            </a>
          </Link>

          <Link href={"/customer/withdraw"}>
            <a className={styles.card}>
              <h2>Withdraw &rarr;</h2>
            </a>
          </Link>

          <Link href={"/customer/manageOverdraft"}>
            <a className={styles.card}>
              <h2>Manage Overdraft &rarr;</h2>
            </a>
          </Link>

          <Link href={"/customer/transfer"}>
            <a className={styles.card}>
              <h2>Make Transfer &rarr;</h2>
            </a>
          </Link>

          <Link href={"/"}>
            <Button fullWidth color="error" variant="contained">
              Back
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}
