import Head from "next/head";
import React, { useEffect, useState } from "react";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { url } from "../../lib/env";
import { useContext, useRef } from "react";
import AppContext from "../../AppContext";
import Link from "next/link";
import {
  Grid,
  Paper,
  TextField,
  Button,
  Typography,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
} from "@mui/material";

export default function deposit(props) {
  const [person, setPerson] = useState("");
  const [accounts, setAccounts] = useState([]);
  const [customers, setCustomers] = useState([]);
  const [account, setAccount] = useState("");
  const [customer, setCustomer] = useState("");
  const [salary, setSalary] = useState(0);
  const [numPayments, setNumPayments] = useState(0);
  const [accumEarnings, setAccumEarnings] = useState(0);
  const { userData, setUserData } = useContext(AppContext);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    const accountIDs = await fetch(
      url + `/api/customer/getAccessibleAccounts`,
      {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          customer: userData.userID,
        }),
      }
    );
    const accountIDsJSON = await accountIDs.json();
    setAccounts(accountIDsJSON);
  };

  const handleDeposit = async () => {
    if (salary <= 0) {
      alert("Cannot Withdraw Negative or 0");
      return;
    }

    let account_parsed = account.split(" / ");
    const rawResponse = await fetch(url + "/api/customer/withdraw", {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        requester: userData.userID,
        amount: salary,
        bankID: account_parsed[1],
        accountID: account_parsed[0],
      }),
    });

    const response = await rawResponse.json();
    if (rawResponse.status === 400) {
      console.log(response.sqlMessage);
      alert(response.sqlMessage);
    } else if (rawResponse.status === 200) {
      alert("Success");
    }
  };

  return userData.userRole.includes("c") ? (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container spacing={1}>
        <Grid item xs={12}>
          <h1 className={styles.title}>Withdraw</h1>
        </Grid>

        <Grid item xs={2} />
        <Grid item xs={8}>
          {accounts && (
            <FormControl fullWidth>
              <InputLabel>Account</InputLabel>
              <Select
                label="Account"
                value={account}
                onChange={(e) => setAccount(e.target.value)}
              >
                {accounts.map((obj, i) => {
                  let acctID = obj["accountID"];
                  let bankID = obj["bankID"];
                  return (
                    <MenuItem key={i} value={acctID + " / " + bankID}>
                      {acctID + " / " + bankID}
                    </MenuItem>
                  );
                })}
              </Select>
            </FormControl>
          )}
        </Grid>
        <Grid item xs={2} />

        <Grid item xs={2} />
        <Grid item xs={8}>
          <TextField
            label="Amount"
            type="number"
            fullWidth
            value={salary}
            onChange={(e) => setSalary(e.target.value)}
          />
        </Grid>
        <Grid item xs={2} />

        <Grid item xs={2} />

        <Grid item xs={4}>
          <Link href="/customer/customerMenu">
            <Button fullWidth variant="contained" color="error">
              Cancel
            </Button>
          </Link>
        </Grid>

        <Grid item xs={4}>
          <Button variant="contained" fullWidth onClick={handleDeposit}>
            Create
          </Button>
        </Grid>
        <Grid item xs={2} />
      </Grid>
    </div>
  ) : (
    <h1>Not Authorized</h1>
  );
}
