import Head from "next/head";
import React, { useState, useContext } from "react";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { url } from "../../lib/env";
import AppContext from "../../AppContext";
import Link from "next/link";

import {
  Grid,
  Paper,
  TextField,
  Button,
  Typography,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
} from "@mui/material";

export default function payEmployees(props) {
  const { userData, setUserData } = useContext(AppContext);

  const handlePayEmployees = async () => {
    const res = await fetch(`/api/payEmployees`);
    if (res.status === 200) {
      alert("Pay Successful");
    } else {
      alert("Pay Failed");
    }
    return null;
  };

  return userData.userRole.includes("e") ? (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container spacing={1}>
        <Grid item xs={12}>
          <h1 className={styles.title}>Pay Employees</h1>
        </Grid>

        <Grid item xs={2} />
        <Grid item xs={8}>
          <Button fullWidth variant="contained" onClick={handlePayEmployees}>
            Pay All Employees
          </Button>
        </Grid>

        <Grid item xs={2} />

        <Grid item xs={2} />
        <Grid item xs={8}>
          <Link href="/manager/managerMenu">
            <Button fullWidth variant="contained" color="error">
              Back
            </Button>
          </Link>
        </Grid>

        <Grid item xs={2} />
      </Grid>
    </div>
  ) : (
    <h1> Not Authorized </h1>
  );
}
