import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { url } from "../../lib/env";
import { TextField, Button } from "@mui/material";
import { useState } from "react";
import Link from "next/link";

export default function AdminMenu() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Admin Menu</h2>

        <div className={styles.grid}>
          <Link href={"/admin/statsMenu"}>
            <a className={styles.card}>
              <h2>View Stats &rarr;</h2>
            </a>
          </Link>

          <Link href={"/admin/createCorporation"}>
            <a className={styles.card}>
              <h2>Create Corporation &rarr;</h2>
            </a>
          </Link>

          <Link href={"/admin/createFee"}>
            <a className={styles.card}>
              <h2>Create Fee &rarr;</h2>
            </a>
          </Link>

          <Link href={"/admin/manageUsers"}>
            <a className={styles.card}>
              <h2>Manage Users &rarr;</h2>
            </a>
          </Link>

          <Link href={"/admin/manageOverdraft"}>
            <a className={styles.card}>
              <h2>Manage Overdraft &rarr;</h2>
            </a>
          </Link>

          <Link href={"/admin/hireWorkerAdmin"}>
            <a className={styles.card}>
              <h2>Hire Worker &rarr;</h2>
            </a>
          </Link>

          <Link href={"/admin/payEmployees"}>
            <a className={styles.card}>
              <h2>Pay Employees &rarr;</h2>
            </a>
          </Link>

          <Link href={"/admin/replaceManager"}>
            <a className={styles.card}>
              <h2>Replace Manager &rarr;</h2>
            </a>
          </Link>

          <Link href={"/admin/manageAccountsAdmin"}>
            <a className={styles.card}>
              <h2>Manage Accounts &rarr;</h2>
            </a>
          </Link>

          <Link href={"/admin/createBank"}>
            <a className={styles.card}>
              <h2>Create Bank &rarr;</h2>
            </a>
          </Link>

          <Link href="/">
            <Button
              variant="contained"
              color="error"
              fullWidth
              style={{ marginBottom: 20 }}
            >
              Back
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}
