import Head from "next/head";
import React from "react";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { url } from "../../lib/env";
import MyTable from "../../components/MyTable";
import Link from "next/link";
import { Button } from "@mui/material";
export async function getServerSideProps() {
  const res = await fetch(url + `/api/getBankView`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default function bankView({ data }) {
  for (let index = 0; index < data.length; index++) {
    data[index].id = index;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Display Bank Stats</h1>
        <MyTable
          columns={[
            { field: "bank_identifier", headerName: "Bank ID", width: 150 },
            {
              field: "name_of_corporation",
              headerName: "Corporation Name",
              width: 150,
            },
            { field: "name_of_bank", headerName: "Bank Name", width: 300 },
            {
              field: "street",
              headerName: "Street",
              width: 200,
            },
            { field: "city", headerName: "City", width: 100 },
            { field: "state", headerName: "State", width: 50 },
            { field: "zip", headerName: "Zip", width: 75 },
            {
              field: "num_accounts",
              headerName: "Number of Accounts",
              type: "number",
              width: 150,
            },
            {
              field: "bank_assets",
              headerName: "Bank Assets ($)",
              type: "number",
              width: 150,
            },
            {
              field: "total_assets",
              headerName: "Total Assets ($)",
              type: "number",
              width: 150,
            },
          ]}
          data={data}
        />

        <Link href="/admin/statsMenu">
          <Button
            variant="contained"
            color="error"
            fullWidth
            style={{ marginBottom: 20 }}
          >
            Back
          </Button>
        </Link>
      </main>
    </div>
  );
}
