import Head from "next/head";
import React from "react";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { url } from "../../lib/env";
import MyTable from "../../components/MyTable";
import Link from "next/link";
import { Button } from "@mui/material";

export async function getServerSideProps() {
  const res = await fetch(url + `/api/getCorporationView`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default function corporationView({ data }) {
  for (let index = 0; index < data.length; index++) {
    data[index].id = index;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Display Corporation Stats</h1>
        <MyTable
          columns={[
            {
              field: "corporation_identifier",
              headerName: "Corporation ID",
              width: 100,
            },
            { field: "short_name", headerName: "Short Name", width: 200 },
            { field: "formal_name", headerName: "Formal Name", width: 300 },
            {
              field: "number_of_banks",
              headerName: "# Banks",
              type: "number",
              width: 150,
            },
            {
              field: "corporation_assets",
              headerName: "Corporation Assets ($)",
              type: "number",
              width: 200,
            },
            {
              field: "total_assets",
              headerName: "Total Assets ($)",
              type: "number",
              width: 200,
            },
          ]}
          data={data}
        />

        <Link href="/admin/statsMenu">
          <Button
            variant="contained"
            color="error"
            fullWidth
            style={{ marginBottom: 20 }}
          >
            Back
          </Button>
        </Link>
      </main>
    </div>
  );
}
