import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { url } from "../../lib/env";
import { TextField, Button } from "@mui/material";
import { useState } from "react";
import Link from "next/link";

export default function manageUsers() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Create Roles</h2>

        <div className={styles.grid}>
          <Link href={"/admin/createEmployee"}>
            <a className={styles.card}>
              <h2>Create Employee &rarr;</h2>
            </a>
          </Link>

          <Link href={"/admin/createCustomer"}>
            <a className={styles.card}>
              <h2>Create Customer &rarr;</h2>
            </a>
          </Link>

          <Link href="/admin/manageUsers">
            <Button
              variant="contained"
              color="error"
              fullWidth
              style={{ marginBottom: 20 }}
            >
              Back
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}
